---
# Globális változók minden host-ra
hf_token: "YOUR_HUGGINGFACE_TOKEN"    # HuggingFace API token
cuda_version: "12.1"                  # Cuda version
docker_version: "latest"              # Docker version (latest suggest)
vllm_version: "0.6.3.post1"          # vLLM version
ray_version: "2.9.3"                  # Ray version
model_id: "huggingface-model/repo"    # Downloadable model

